### ISSUE TITLE
Custom editors

### ISSUE THREAD

**Issue by jperon** [DataGridXL/DataGridXL#118]
Hello,

First let me thank you for this very good piece of software!
Seeing #8 closed, I was wondering whether it was possible to define custom editors, especially autocomplete and date picker.
Thank you again!

**Comment by jperon** [comment]
Sorry, didn’t see that this repository was obsolete. Sorry for the noise.

**Comment by DataGridXL** [comment]
Hi,

Thanks for reaching out!

Version 3 of DataGridXL (march 2024) will have autocomplete and date picker abilities.
