### ISSUE TITLE
Allow `new DataGridXL()` to take a dom node, not just an id string.

### ISSUE THREAD

**Issue by boxxxie** [DataGridXL/DataGridXL#12]
i found this pretty confusing when starting out with the API.

also i don't know how to get a datagrid instance from a dom node, would be great if there were an example of how to do so.

**Comment by RobbiesCode** [comment]
Hi Boxxxie,

Thanks for your suggestion!

We're working hard on [DGXL v2](https://www.datagridxl.com/v2-coming-soon). In v2, `new DataGridXL()` will accept an id string or a DOM node, just like your suggestion. For v1, this is a **wontfix**, as we have decided to only fix breaking errors for v1, until v2 comes out.

The easiest way to get a DGXL instance would be to store it in a `var` when creating a new DataGridXL:

```
var grid = new DataGridXL("grid", {
  // options ...
});
```

The DataGridXL instances are stored in `DataGridXL.instances`, which is an array that holds all DGXL instances on your page. To get your grid's container node, you can do so by looking up `DataGridXL.instances[0]._domNodes.containerNode`.

Hope this helps!
