### ISSUE TITLE
DGXL2: Custom Context Menu not visible in full screen mode

### ISSUE THREAD

**Issue by RobbiesCode** [DataGridXL/DataGridXL#15]
The context menu needs to be a child of the HTMLElement that is in fullscreen, in our case "componentNode". Our context menu is usually a direct child of <body> for good reasons (ignoring any overflow:hidden rules).

Move the context menu container node to be a child of our fullscreen element when full screen opens, then move it back to <body> when fullscreen closes.

**Comment by DataGridXL** [comment]
Fixed. Changes in handleDocumentFullscreenChange.
