### ISSUE TITLE
Prevent Google Translate from messing up component

### ISSUE THREAD

**Issue by RobbiesCode** [DataGridXL/DataGridXL#7]
Go to https://www.datagridxl.com/compare/handsontable

Translate the page using G Translate. This affects the DGXL instance, and scrolling too. Perhaps use the "translate=no" attribute on the cell values node?

https://stackoverflow.com/questions/9628507/how-can-i-tell-google-translate-to-not-translate-a-section-of-a-website

**Comment by DataGridXL** [comment]
Will be fixed in v3 with `translate="no"`
