### ISSUE TITLE
IDEA thread (features)

### ISSUE THREAD

**Issue by RobbiesCode** [DataGridXL/DataGridXL#8]
### Feature Ideas

Columns:
- Readonly columns
- Validation (like Handsontable? https://handsontable.com/docs/8.0.0/demo-data-validation.html)
- Formatting:
"5" becomes 5 star emojis (⭐⭐⭐⭐⭐), ".5" becomes "50%", true/false becomes ✔️❌, etc
- Custom Editors:
date picker,
select/auto-complete

Document:
- Fixed Columns
- Fixed Rows

Search/Filter:
- Column Filters
- Search Table
- Sorting (by clicking headers)

Misc:
- Paging
- Save state
- Column Header Spans (v2?)
- Tree View (v2?)
- Make emails/link clickable (column type)

v1 should really stay the best Excel-like 2D array **editor**.

**Comment by Kleissner** [comment]
Search is the most important function for us - we would get a paid license if it supports search. Until then, we continue with jexcel, which has poor performance (it loves to freeze the entire page while it's loading data).

**Comment by RobbiesCode** [comment]
Hi Kleissner,

Thanks for reaching out! Performance issues in other grids were the main reason for me to build this product, so I am glad it shows!

Let me tell you the state of DataGridXL as of today:

A month ago I realized that I wanted the product to appeal to a larger audience, so I took all the good stuff from DGXL and started working on Abletable (not online yet). Abletable will have two modes: output mode (like DataTables) and input mode (like DataGridXL).

Abletable will do everything that DataGridXL already does, but adds (at least) the following features:

* Search Cell (just like CTRL+F for Google Sheets)
* Search Filter (like DataTables search function)
* Multi-column sorting
* Smooth scroll, not just scroll snap (for better usability on touch screens)
* Improved touch controls and added features
* Frozen/fixed columns and rows

It will keep its focus on performance, usability and simplicity. The core concept does not change.

I am nearly done with the search function of Abletable and it works just like Google Sheets CTRL+F pop over. That said, it's hard to tell when Abletable will be done, but I am targeting April. I hope that's not too late for you.

I would also like to mention that if you purchase a DataGridXL license, it will be automatically converted to an Abletable license, no extra charges.

Hope this helps. Let me know if you have any questions!

**Comment by RobbiesCode** [comment]
> Search is the most important function for us - we would get a paid license if it supports search. Until then, we continue with jexcel, which has poor performance (it loves to freeze the entire page while it's loading data).

Just wanted to let everybody know that Search is coming to DGXL v2 (Q3): https://www.datagridxl.com/v2-coming-soon

**Comment by DataGridXL** [comment]
@Kleissner Just wanted to let you know that we have released DataGridXL2 yesterday. It includes a very fast search bar! See https://github.com/DataGridXL/DataGridXL2.
